### ISSUE TITLE
Timed out receiving message from renderer: 600.000

### ISSUE THREAD

**Issue by amony-ot** [markhobson/docker-maven-chrome#32]
Getting timeout exceptions when using the ChromeDriver. It was working fine without any issues on Jan, but recently i'm getting timeout exceptions after updating the driver to 89 version.

```
Starting ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}) on port 21305
All remote connections are allowed. Use an allowlist instead!
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1617637257.090][SEVERE]: Timed out receiving message from renderer: 600.000
```

**Comment by markhobson** [comment]
Can you explain how you're using this image please? You say you've updated ChromeDriver to 89 but this is managed in the image. 

Also, does this log message result in an exception? In #20 it was essentially a warning.

**Comment by amony-ot** [comment]
This was the final error message -> 
ChromeDriver was started successfully.
ERROR: Job failed: execution took longer than 1h0m0s seconds.

I'm using this image in gitlab-ci.yml.

**Comment by amony-ot** [comment]
Looks like Chrome driver has this issue,

ChromeDriver 89.0.4389.23
Supports Chrome version 89

**Resolved issue 3667: Timed out receiving a message from renderer**
Resolved issue 3675: GetElementLocation uses inView method which mishandles boolean as array
Resolved issue 3682: GetElementRegion returns incorrect size for elements which are partially out of viewport
Resolved issue 3690: ChromeDriver fails if extensions use chrome.windows API

**Comment by markhobson** [comment]
That's the version of ChromeDriver currently in this image, but you're still seeing this message?

**Comment by amony-ot** [comment]
Yes i'am.

**Comment by markhobson** [comment]
Can you provide a minimal project that reproduces the problem?

**Comment by markhobson** [comment]
Closing until details on reproducing the problem are provided.

**Comment by amony-ot** [comment]
Issue fixed after updating the image to the latest JDK -16.
